### ISSUE TITLE
GitHub pages not building

### ISSUE THREAD

**Issue by sjlewis-jpl** [nasa-opera/nasa-opera.github.io#3]
Commits to the `main` branch triggers the build & deploy pipeline.  The logs seem to show everything working properly, and shows the site being successfully deployed.  However, I get a 404 error when trying to visit the page.

@riverma - do you have any insight on what might be causing the issue?  I have tried pushing new commits to try and get it to rebuild and redeploy (as suggested by some web searches), and looked through the build logs, but don't have any clues.  If you've seen this before and have any advice, I would really appreciate it.

**Comment by boris-ning-usds** [comment]
Can you try switching your [baseUrl](https://github.com/nasa-opera/nasa-opera.github.io/blob/main/docusaurus.config.js#L19) to `baseUrl: '/nasa-opera.github.io/'`.

When I build and run it locally using `npm install && npm run build && npm run serve`, navigating to http://localhost:3000 doesn't present a default website either, it's a 404 website.

If I switch the baseUrl, it does properly navigate.

**Comment by sjlewis-jpl** [comment]
Hi Boris - thank you for the suggestion.  I was just in the middle of following another idea, but I will try that next, and let you know if that fixes the issue.

On my local machine, I'm using `yarn` to make pages on localhost, which works with the current setup.  But I'll switch to `npm` if that ends up being more robust.

**Comment by boris-ning-usds** [comment]
Oh, there shouldn't be any difference between using `npm` or `yarn`. Defining the route in the docusaurus configuration is the important part.
