### ISSUE TITLE
Broken link on https://www.jpl.nasa.gov/go/opera/

### ISSUE THREAD

**Issue by boris-ning-usds** [nasa-opera/nasa-opera.github.io#4]
Hi, 

I was just stumbling around https://www.jpl.nasa.gov/go/opera/ and noticed that the "data products page" link is broken.
It navigates to https://www.jpl.nasa.gov/go/opera/products which is 404'ing.
![image](https://github.com/user-attachments/assets/3bb73561-609e-4788-b906-02e270e074f8)

Would you happen to have access to the site editors - Tony Greicius, Naomi Hartono (at the bottom of that page) to fix that URL?

I figured this is a shorter path to figuring out how to contact them.
Thanks.

**Comment by sjlewis-jpl** [comment]
Hi @boris-ning-usds - that link is working for me.  Perhaps that was just a transient issue?

In general, yes, I can reach the site editors if there's an issue.

**Comment by boris-ning-usds** [comment]
Oh, now it's working. It was giving me a 404 before.

Thanks, all good here.
